Repository alejmedinajr/AI-Detector, pull requests merged in 2024-02, with the labels that each got.

#29 Adding new Bard/Gemini endpoint to API
  API.py
Labels: Back-End

#36 Improved documentation in certain areas
  API.py
  main-react-app/src/App.js
  main-react-app/src/PromptForm.js
Labels: documentation, Normal

#35 34 set up database integration with fastapi
  .gitignore
  cs_faculty.json
  database.py
Labels: Normal

#40 37 file upload feature
  API.py
  main-react-app/src/App.js
  main-react-app/src/components/FileForm.js
Labels: Normal

#42 38 file parsingtext parsing
  .gitignore
  API.py
  main-react-app/package-lock.json
  main-react-app/package.json
  main-react-app/src/App.js
  main-react-app/src/PromptForm.js
  main-react-app/src/components/FileForm.js
  main-react-app/src/components/PromptForm.js
  main-react-app/src/index.js
  parsing.py
Labels: Back-End, Normal
